name: Build and push

on:
  push:
    branches:
      - 'main'

  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Install tar
        run: apt-get install tar -y
      - name: Prepare multiscraper
        run: mkdir multiscrape && curl https://codeload.github.com/danieldotnl/ha-multiscrape/tar.gz/master | \ tar --directory multiscrape -xz --strip=2 ha-multiscrape-master/custom_components/multiscrape
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: max4711/hascraper:latest